# serverless.yml

service: express-app

provider:
  name: aws
  runtime: nodejs18.x
  stage: staging
  region: ap-southeast-3
  
functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      # - http: 'ANY {proxy+}'